require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "say hello to everyone"
task :say_hi do
    puts "Hello Mod One!"
end

desc "build author table"
task :create_authors do 
    sql = <<-SQL
        CREATE TABLE authors(
            id integer PRIMARY KEY,
            name text
        )
    SQL
    DB.execute(sql)

end